language: csharp
solution: MongoData.sln
services:
    - mongodb

branches:
  # whitelist
  only:
    - master

matrix:
  include:
    - os: linux # Ubuntu 18.04
      dist: bionic
      sudo: required
      mono: none
      dotnet: 2.1.803
#    - os: osx # OSX 10.11
#      osx_image: xcode7.3
#      mono: none
#      dotnet: 2.1.509

before_script:
    - if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "[skip travis]" ; then echo "[skip travis] has been found, exiting" && exit 0 ; else echo "[skip travis] has not been found, continuing" ; fi
    - sleep 5

script:
    - artifactsFolder="./artifacts"
    - if [ -d $artifactsFolder ]; then rm -R $artifactsFolder; fi
    - dotnet restore && dotnet build test/MongoData.Tests
    - dotnet test test/MongoData.Tests