language: csharp
solution: MongoData.sln
services:
    - mongodb

branches:
  # whitelist
  only:
    - master

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      mono: none
      dotnet: 1.0.0-preview2-003131
#    - os: osx # OSX 10.11
#      osx_image: xcode7.3
#      mono: none
#      dotnet: 1.0.0-preview2-003131

before_script:
    - sleep 5

script:
    - artifactsFolder="./artifacts"
    - if [ -d $artifactsFolder ]; then rm -R $artifactsFolder; fi
    - dotnet restore && dotnet build **/project.json
    - dotnet test test/MongoData.Tests