image: Visual Studio 2019
services:
    - mongodb

branches:
  # whitelist
  only:
    - master

build_script:
    - set artifactsFolder=.\artifacts
    - if exist "%artifactsFolder%\" rd /q /s "%artifactsFolder%"
    - dotnet restore && dotnet build test/MongoData.Tests

test_script:
    - dotnet test test/MongoData.Tests